openapi: 3.0.0
info:
  version: 1.0.0
  title: CPIC Phenytoin Recommendations based on CYP2C9 and HLA-B phenotypes
  description: >-
    KGrid CPIC guidelines CYP2C9 and HLA-B Phenotypes to Phenytoin
    Recommendation
servers:
  - url: /99999/fk4qz3fz89/v0.1.0
    description: >-
      KGrid CPIC guidelines CYP2C9 and HLA-B Phenotypes to Phenytoin
      Recommendation
tags:
  - name: KO Endpoints
    description: >-
      KGrid CPIC guidelines CYP2C9 and HLA-B Phenotypes to Phenytoin
      Recommendation
paths:
  /dosingrecommendation:
    post:
      tags:
        - KO Endpoints
      description: Retrieve Dosing Recommendation based on the pheno type.
      operationId: recomm
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/phenotype'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dosingrecommendation'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    phenotype:
      required:
        - HLA-B
        - CYP2C9
      properties:
        HLA-B:
          type: object
          required:
            - diplotype
            - phenotype
          properties:
            diplotype:
              type: string
              example: '*15:02/*1'
            phenotype:
              type: string
              example: ''
        CYP2C9:
          type: object
          required:
            - diplotype
            - phenotype
          properties:
            diplotype:
              type: string
              example: '*1/*1'
            phenotype:
              type: string
              example: Extensive metabolizer
    dosingrecommendation:
      required:
        - result
      properties:
        result:
          type: object
          required:
            - type
            - drug
            - phenotype
            - recommendation
          properties:
            type:
              type: string
              example: CPIC Recommendation
            drug:
              type: string
              example: phenytoin
            genes:
              type: object
              required:
                - HLA-B
                - CYP2C9
              properties:
                HLA-B:
                  type: object
                  required:
                    - diplotype
                    - phenotype
                  properties:
                    diplotype:
                      type: string
                      example: '*15:02/*1'
                    phenotype:
                      type: string
                      example: ''
                CYP2C9:
                  type: object
                  required:
                    - diplotype
                    - phenotype
                  properties:
                    diplotype:
                      type: string
                      example: '*1/*1'
                    phenotype:
                      type: string
                      example: Extensive metabolizer
            recommendation:
              type: object
              required:
                - implication
                - content
                - classification
              properties:
                implication:
                  type: string
                  example: ''
                content:
                  type: string
                  example: ''
                classification:
                  type: string
                  example: ''
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
