openapi: 3.0.0
info:
  version: 1.0.0
  title: CPIC CYP2C19 escitalopram recommendations
  description: CPIC recommendations for escitalopram based on CYP2C19 phenotype
servers:
  - url: /99999/fk4d22836l/v0.1.0
    description: CPIC recommendations for escitalopram based on CYP2C19 phenotype
tags:
  - name: KO Endpoints
    description: KGrid CPIC guidelines CYP2C19 Phenotype to Recommendation Endpoints
paths:
  /dosingrecommendation:
    post:
      tags:
        - KO Endpoints
      description: Retrieve Dosing Recommendation based on the pheno type.
      operationId: recomm
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/phenotype'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dosingrecommendation'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    phenotype:
      required:
        - CYP2C19
      properties:
        CYP2C19:
          type: object
          required:
            - diplotype
            - phenotype
          properties:
            diplotype:
              type: string
              example: '*1/*1'
            phenotype:
              type: string
              example: Normal metabolizer
    dosingrecommendation:
      required:
        - result
      properties:
        result:
          type: object
          required:
            - type
            - drug
            - phenotype
            - recommendation
          properties:
            type:
              type: string
              example: CPIC Recommendation
            drug:
              type: string
              example: escitalopram
            genes:
              type: object
              required:
                - CYP2C19
              properties:
                CYP2C19:
                  type: object
                  required:
                    - diplotype
                    - phenotype
                  properties:
                    diplotype:
                      type: string
                      example: '*1/*1'
                    phenotype:
                      type: string
                      example: normal metabolizer
            recommendation:
              type: object
              required:
                - implication
                - content
                - classification
              properties:
                implication:
                  type: string
                  example: ''
                content:
                  type: string
                  example: ''
                classification:
                  type: string
                  example: ''
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
