openapi: 3.0.0
info:
  version: 1.0.0
  title: 'CPIC - Genotype to Phenotype for CYP2D6'
  description: 'KGrid CPIC guidelines Genotype to Phenotype for CYP2D6'
servers:
  - url: '/99999/fk49z9gr7p/v0.0.5/'
    description: 'KGrid CPIC guidelines Genotype to Phenotype for CYP2D6'
tags:
  - name: KO Endpoints
    description: KGrid CPIC guidelines Genotype to Phenotype for CYP2D6 Endpoints
paths:
  /phenotype:
    post:
      tags:
       - KO Endpoints
      description: Determine the pheno type based on the genotype.
      operationId: pheno
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/genotype'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/phenotype'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    genotype:
      required:
      - CYP2D6
      properties:
       CYP2D6:
          type: string
          example: '*3/*3'
    phenotype:
      required:
        - CYP2D6
      properties:
        CYP2D6:
          type: string
          example: 'Poor metabolizer'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
