openapi: 3.0.0
info:
  version: 1.0.0
  title: CPIC Geno Pheno KO Table
  description: >-
    CPIC Geno2Pheno KO Table, with total of 15 entries, which can be filtered by
    supplying a list of genes.
servers:
  - url: /99999/fk4qj7sz2t/v0.1.0
    description: CPIC Geno Pheno KO Table
tags:
  - name: KO Endpoints
    description: CPIC Geno Pheno KO Table
paths:
  /genophenokolist:
    post:
      tags:
        - KO Endpoints
      description: Get the filtered gene2pheno ko list.
      operationId: genophenokolist
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/phenotype'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genophenokolist'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    phenotype:
      type: object
      properties:
        CYP2D6:
          type: string
          example: Normal metabolizer
        CYP2C19:
          type: string
          example: Normal metabolizer
        UGT1A1:
          type: string
          example: Normal metabolizer
    genophenokolist:
      required:
        - result
      properties:
        result:
          type: object
          example:
            CYP2D6: ''
            CYP2C19: ''
            UGT1A1: ''
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
