openapi: 3.0.0
info:
  version: '1.0'
  title: CPIC doxepin Recommendations based on CYP2C19 and CYP2D6 phenotypes
  description: >-
    KGrid CPIC guidelines CYP2C19 and CYP2D6 Phenotypes to doxepin
    Recommendation
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/fk4sf40t7f/1.0
    description: >-
      KGrid CPIC guidelines CYP2C19 and CYP2D6 Phenotypes to doxepin
      Recommendation
tags:
  - name: KO Endpoints
    description: >-
      KGrid CPIC guidelines CYP2C19 and CYP2D6 Phenotypes to doxepin
      Recommendation
paths:
  /dosingrecommendation:
    post:
      tags:
        - KO Endpoints
      description: Retrieve Dosing Recommendation based on the pheno type.
      operationId: recomm
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/phenotype'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dosingrecommendation'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    phenotype:
      required:
        - CYP2D6
        - CYP2C19
      properties:
        CYP2D6:
          type: object
          required:
            - diplotype
            - phenotype
          properties:
            diplotype:
              type: string
              example: '*3/*3'
            phenotype:
              type: string
              example: Poor metabolizer
        CYP2C19:
          type: object
          required:
            - diplotype
            - phenotype
          properties:
            diplotype:
              type: string
              example: '*1/*1'
            phenotype:
              type: string
              example: Normal metabolizer
    dosingrecommendation:
      required:
        - result
      properties:
        result:
          type: object
          required:
            - type
            - drug
            - phenotype
            - recommendation
          properties:
            type:
              type: string
              example: CPIC Recommendation
            drug:
              type: string
              example: doxepin
            genes:
              type: object
              required:
                - CYP2D6
              properties:
                CYP2D6:
                  type: object
                  required:
                    - diplotype
                    - phenotype
                  properties:
                    diplotype:
                      type: string
                      example: '*3/*3'
                    phenotype:
                      type: string
                      example: poor metabolizer
            recommendation:
              type: object
              required:
                - implication
                - content
                - classification
              properties:
                implication:
                  type: string
                  example: ''
                content:
                  type: string
                  example: ''
                classification:
                  type: string
                  example: ''
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
