openapi: 3.0.0
info:
  version: 1.0.0
  title: CPIC - Genotype to Phenotype for CYP2D6
  description: KGrid CPIC guidelines Genotype to Phenotype for CYP2C19
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/fk4mc97w0h/v0.0.2/
    description: KGrid CPIC guidelines Genotype to Phenotype for CYP2C19
tags:
  - name: KO Endpoints
    description: KGrid CPIC guidelines Genotype to Phenotype for CYP2C19 Endpoints
paths:
  /getphenotype:
    post:
      tags:
        - KO Endpoints
      description: Determine the pheno type based on the genotype.
      operationId: pheno
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/genoinputs'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/phenotypeobj'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    genoinputs:
      required:
        - enzyme
        - allele1
        - allele2
      properties:
        enzyme:
          type: string
          example: CYP2C19
        allele1:
          type: string
          example: '*1'
        allele2:
          type: string
          example: '*1'
    phenotypeobj:
      required:
        - enzyme
        - phenotype
      properties:
        enzyme:
          type: string
          example: CYP2D6
        phenotype:
          type: string
          example: Normal metabolizer
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
