
def getGuideline(instr):
	if not instr["allele1"] or not instr["allele2"]:
		#input does not include proper allele keys
		raise Exception("Input must contain keys 'allele1' and 'allele2'")

	allele1 = instr["allele1"]
	allele2 = instr["allele2"]


	info = lookup(allele1 + "/" + allele2)

	if info == -1:
		raise Exception("Invalid allele pair")

	mr = info['genotype_summary']

	guideline = {}

	metabolizerKey = "metabolic_rate"
	implicationsKey = "implications"
	reccomendationKey = "reccomendations"
	alternativesKey = "alternatives"
	reccomendationWeightKey = "recomendation_classification"


	guideline[metabolizerKey] = mr

	if mr == "None" or mr == "Indeterminate":
		guideline[reccomendationKey] = "This guideline does not contain recommendations for this allele combination"
		guideline[implicationsKey] = "N/A"
		guideline[alternativesKey] = []
		guideline[reccomendationWeightKey] = "N/A"

	elif 'Intermediate' in mr:
		# print "ITS INTERMEDIATE DAWG"
		guideline[reccomendationKey] = "Prescribe a lower dose or consider an alternative statin. Consider routine CK surveillance"
		guideline[implicationsKey] = "Intermediate myopathy risk"
		guideline[alternativesKey] = ["pravastatin", "rosuvastatin"]
		guideline[reccomendationWeightKey] = "Strong"
	elif "Increased" in mr:
		# print "INCREASED YO"
		guideline[reccomendationKey] = "No specific reccomendations. Consult a clinical pharmacist"
		guideline[implicationsKey] = ""
		guideline[alternativesKey] = []
		guideline[reccomendationWeightKey] = "Strong"

	elif "Low" in mr:
		# print "ITS LO DAWG"
		guideline[reccomendationKey] = "Prescribe a lower dose or consider an alternative statin. Consider routine CK surveillance"
		guideline[implicationsKey] = "High myopathy risk"
		guideline[alternativesKey] = ["pravastatin", "rosuvastatin"]
		guideline[reccomendationWeightKey] = "Strong"

	return str(guideline)







def lookup(allelePair):
	'''
		this enormous lookup dictionary was created by a seperate script that parses through an Excel
		document that conained all of the mappings. I turned it into a python dictinary and put it here

		It contains about 700 keys.

		The Excel sheet along with the published guideline can be found at https://www.pharmgkb.org/guideline/PA166105005

		Code for the rest of this function is:

				if allelePair in guide:
					return guide[allelePair]
				else:
					return -1

		It checks if the pair is in the lookup dictionary. It will reutrn -1 to signal invalid pair
		if you give it a pair that is not in the table


		Scrolling past this point not reccomended.
	'''

	guide = {
		'*10/*10': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*10/*11': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*12': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*13': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*14': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*15': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*10/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*17': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*10/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*23': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*10/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*10/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*10/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*11': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*12': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*13': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*14': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*15': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*17': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*11/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*12': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*13': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*14': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*15': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*17': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*12/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*13': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*14': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*15': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*17': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*13/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*14': {'genotype_summary': 'SLCO1B1 - Possible Increased Function',
		             'priority_result': 'None'},
		 '*14/*15': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*17': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*14/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*15': {'genotype_summary': 'SLCO1B1 - Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*15/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*17': {'genotype_summary': 'SLCO1B1 - Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*15/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*23': {'genotype_summary': 'SLCO1B1 -Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*15/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*31': {'genotype_summary': 'SLCO1B1 -Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*15/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*15/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*17': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*16/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*17': {'genotype_summary': 'SLCO1B1 - Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*17/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*23': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*17/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*17/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*17/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*18/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*19/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*10': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*11': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*12': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*13': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*14': {'genotype_summary': 'SLCO1B1 - Possible Increased Function',
		             'priority_result': 'None'},
		 '*1a/*15': {'genotype_summary': 'SLCO1B1 - Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*17': {'genotype_summary': 'SLCO1B1 - Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*1a': {'genotype_summary': 'None',
		             'priority_result': 'Normal/Routine/Low Risk'},
		 '*1a/*1b': {'genotype_summary': 'None',
		             'priority_result': 'Normal/Routine/Low Risk'},
		 '*1a/*2': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*23': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*3': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*31': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*35': {'genotype_summary': 'SLCO1B1 - Possible Increased Function',
		             'priority_result': 'None'},
		 '*1a/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1a/*4': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*1a/*5': {'genotype_summary': 'SLCO1B1- Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*6': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1a/*7': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*1a/*8': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*1a/*9': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*10': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*11': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*12': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*13': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*14': {'genotype_summary': 'SLCO1B1 - Possible Increased Function',
		             'priority_result': 'None'},
		 '*1b/*15': {'genotype_summary': 'SLCO1B1 - Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*16': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*17': {'genotype_summary': 'SLCO1B1 - Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*18': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*19': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*1b': {'genotype_summary': 'None',
		             'priority_result': 'Normal/Routine/Low Risk'},
		 '*1b/*2': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*23': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*3': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*31': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*35': {'genotype_summary': 'SLCO1B1 - Possible Increased Function',
		             'priority_result': 'None'},
		 '*1b/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*1b/*4': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*1b/*5': {'genotype_summary': 'SLCO1B1- Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*6': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*1b/*7': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*1b/*8': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*1b/*9': {'genotype_summary': 'SLCO1B1 - Possible Intermediate Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*10': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*11': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*12': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*13': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*14': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*15': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*16': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*17': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*18': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*19': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*2': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*20': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*21': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*22': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*23': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*24': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*25': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*26': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*27': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*28': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*29': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*3': {'genotype_summary': 'SLCO1B1- Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*30': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*32': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*33': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*34': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*35': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*36': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*2/*4': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*2/*5': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*6': {'genotype_summary': 'SLCO1B1- Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*2/*7': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*2/*8': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*2/*9': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*20/*20': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*20/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*21': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*21/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*22': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*23': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*22/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*23': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*23/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*23/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*23/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*24': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*24/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*25': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*25/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*26': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*26/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*27': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*27/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*28': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*28/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*29/*29': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*29/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*29/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*29/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*29/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*29/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*29/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*29/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*3/*10': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*3/*11': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*12': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*13': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*14': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*15': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*3/*16': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*17': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*3/*18': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*19': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*20': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*21': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*22': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*23': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*3/*24': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*25': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*26': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*27': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*28': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*29': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*3': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*3/*30': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*3/*32': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*33': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*34': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*35': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*36': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*3/*4': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*3/*5': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*3/*6': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*3/*7': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*3/*8': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*3/*9': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*30/*30': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*30/*31': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*30/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*30/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*30/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*30/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*30/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*31/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		             'priority_result': 'Abnormal/Priority/High Risk'},
		 '*31/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*31/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*31/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*31/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*31/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*32/*32': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*32/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*32/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*32/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*32/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*33/*33': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*33/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*33/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*33/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*34/*34': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*34/*35': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*34/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*35/*35': {'genotype_summary': 'SLCO1B1 - Possible Increased Function',
		             'priority_result': 'None'},
		 '*35/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*36/*36': {'genotype_summary': 'Indeterminate',
		             'priority_result': 'None'},
		 '*4/*10': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*11': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*12': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*13': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*14': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*15': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*16': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*17': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*18': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*19': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*20': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*21': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*22': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*23': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*24': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*25': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*26': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*27': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*28': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*29': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*30': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*31': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*32': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*33': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*34': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*35': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*36': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*4/*4': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*4/*5': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*4/*6': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*4/*7': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*4/*8': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*4/*9': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*5/*10': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*5/*11': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*12': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*13': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*14': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*15': {'genotype_summary': 'SLCO1B1 - Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*5/*16': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*17': {'genotype_summary': 'SLCO1B1 - Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*5/*18': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*19': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*20': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*21': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*22': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*23': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*5/*24': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*25': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*26': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*27': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*28': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*29': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*30': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*5/*32': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*33': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*34': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*35': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*36': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*5/*5': {'genotype_summary': 'SLCO1B1 - Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*5/*6': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*5/*7': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*5/*8': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*5/*9': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*6/*10': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*6/*11': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*12': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*13': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*14': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*15': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*6/*16': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*17': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*6/*18': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*19': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*20': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*21': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*22': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*23': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*6/*24': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*25': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*26': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*27': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*28': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*29': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*30': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*6/*32': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*33': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*34': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*35': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*36': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*6/*6': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*6/*7': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*6/*8': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*6/*9': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'},
		 '*7/*10': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*11': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*12': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*13': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*14': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*15': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*16': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*17': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*18': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*19': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*20': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*21': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*22': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*23': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*24': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*25': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*26': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*27': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*28': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*29': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*30': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*31': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*32': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*33': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*34': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*35': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*36': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*7/*7': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*7/*8': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*7/*9': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*8/*10': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*11': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*12': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*13': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*14': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*15': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*16': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*17': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*18': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*19': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*20': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*21': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*22': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*23': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*24': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*25': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*26': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*27': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*28': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*29': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*30': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*31': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*32': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*33': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*34': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*35': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*36': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*8/*8': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*8/*9': {'genotype_summary': 'Indeterminate',
		           'priority_result': 'None'},
		 '*9/*10': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*9/*11': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*12': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*13': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*14': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*15': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*9/*16': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*17': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*9/*18': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*19': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*20': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*21': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*22': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*23': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*9/*24': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*25': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*26': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*27': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*28': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*29': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*30': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*31': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		            'priority_result': 'Abnormal/Priority/High Risk'},
		 '*9/*32': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*33': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*34': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*35': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*36': {'genotype_summary': 'Indeterminate',
		            'priority_result': 'None'},
		 '*9/*9': {'genotype_summary': 'SLCO1B1 - Possible Low Function',
		           'priority_result': 'Abnormal/Priority/High Risk'}
		}

	if allelePair in guide:
		return guide[allelePair]
	else:
		return -1


