openapi: 3.0.0
info:
  version: 1.0.0
  title: 'CPIC CYP2D6 Codeine Recommendations'
  description: 'KGrid CPIC guidelines CYP2D6 Phenotype to Recommendation'
servers:
  - url: '/99999/fk4mc97w6m/v0.0.2/'
    description: 'KGrid CPIC guidelines CYP2D6 Phenotype to Recommendation'
tags:
  - name: KO Endpoints
    description: KGrid CPIC guidelines CYP2D6 Phenotype to Recommendation Endpoints
paths:
  /getrecommendation:
    post:
      tags:
       - KO Endpoints
      description: Retrieve Dosing Recommendation based on the pheno type.
      operationId: recomm
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/phenotypeobj'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dosingrecouput'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    phenotypeobj:
      required:
        - enzyme
        - phenotype
      properties:
        enzyme:
          type: string
          example: 'CYP2D6'
        phenotype:
          type: string
          example: 'Normal metabolizer'
    dosingrecouput:
      required:
        - result
      properties:
        result:
          type: object
          example: {"enzyme":"CYP2D6","drug":"Codeine","recommendation":{}}
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
